added all contributers in readme
keploy/keploy pull request #101
Opened 2022-04-01 13:51 UTC by Ayush7614

Added all contributers in readme

2022-04-01 13:54 UTC, Ayush7614 commented
cc @nehagup @slayerjain

2022-04-02 05:08 UTC, nehagup commented
@Ayush7614 Is there any way to do this automatically? Right now my understanding is, you've added these entries manually.

2022-04-02 07:24 UTC, Ayush7614 commented
> @Ayush7614 Is there any way to do this automatically? Right now my understanding is, you've added these entries manually.

No for manually i have doing previously
![image](https://user-images.githubusercontent.com/67006255/161372041-73810007-b4aa-41f8-b7a1-193751c3a707.png)

2022-04-02 07:25 UTC, Ayush7614 commented
Like This

2022-04-03 17:16 UTC, slayerjain commented
@Ayush7614 better solution would have be if this feature is available in contrib.rocks  - https://github.com/lacolaco/contributors-img/issues/1036

2022-04-05 19:21 UTC, nehagup commented
@Ayush7614 Looks like the changes vanished :(

2022-04-06 20:10 UTC, Ayush7614 commented
cc @nehagup

2022-04-07 07:58 UTC, nehagup requested changes
@Ayush7614 the list of contributors added doesn't seem correct :(

2022-04-07 07:58 UTC, nehagup commented on README.md
> +<td align="center"><a href="https://github.com/praneshr"><img src="https://avatars.githubusercontent.com/u/10805204?v=4" width="100px;" alt=""/><br /><sub><b>Pranesh Ravi</b></sub></a><br /><a href="
I couldn't find these users contributions to Keploy. Where did you get this from, please help. 🤔

2022-04-07 07:58 UTC, nehagup commented on README.md
> -## 📌 Our valuable Contributors👩‍💻👨‍💻 :
Please keep this line. And in the next line what is [emoji key] for?

2022-04-07 18:42 UTC, nehagup approved these changes

2022-04-07 18:44 UTC, nehagup commented
IMO we added everyone. Please feel free to add more contributors if missed any.

2022-04-07 18:44 UTC, merged