feat: add repo options in issue template
keploy/keploy pull request #1229
Opened 2023-12-20 17:14 UTC by officialasishkumar

## Related Issue
  Added more repository options in issue template

Closes: #1227 

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change
Feature

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

2023-12-20 17:14 UTC, officialasishkumar commented
@Arindam200, PTAL

2023-12-20 17:32 UTC, Arindam200 requested changes

2023-12-20 17:32 UTC, Arindam200 commented on .github/ISSUE_TEMPLATE/--feature-request.yaml
> +        - samples-typescript
Please Remove the extra Indentation.

2023-12-21 08:56 UTC, Sonichigo approved these changes

2023-12-21 08:56 UTC, merged