refactor:remove redudant workflows and removed serve package
keploy/keploy pull request #1432
Opened 2024-01-25 09:02 UTC by EraKin575

## Related Issue
  - Info about Issue or bug

Closes: #1430

#### Describe the changes you've made
A clear and concise description of what you have done to successfully close your assigned issue. Any new files? or anything you feel to let us know!

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [ ] My code follows the style guidelines of this project.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

2024-01-25 12:18 UTC, PranshuSrivastava requested changes

2024-01-25 12:21 UTC, PranshuSrivastava commented on .github/workflows/test_workflow_scripts/golang-linux.sh
>  # Start the gin-mongo app in test omde.
Please fix this typo as well

2024-01-25 19:38 UTC, Sarthak160 commented
@EraKin575 Java workflow is breaking, and since @PranshuSrivastava stated we should now use `java -jar "path-to-jar"` command instead of mvn run.

2024-01-27 09:54 UTC, PranshuSrivastava requested changes

2024-01-27 09:54 UTC, PranshuSrivastava commented on .github/workflows/test_workflow_scripts/python-linux.sh
> -source ./../../../.github/workflows/test_workflow_scripts/test-iid.sh
Please add this back as well.

2024-01-28 09:15 UTC, Sarthak160 approved these changes
Ship it

2024-01-28 09:20 UTC, PranshuSrivastava approved these changes
LGTM

2024-01-28 09:21 UTC, merged