feat: debugger guide
keploy/keploy pull request #1446
Opened 2024-01-29 08:39 UTC by officialasishkumar

## Related Issue
  Added debugger guide

Closes: #1002 

#### Describe the changes you've made
Added Debugger guide

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

2024-02-08 07:30 UTC, officialasishkumar commented
@shivamsouravjha Please take a look

2024-02-10 13:07 UTC, PranshuSrivastava requested changes

2024-02-10 13:07 UTC, PranshuSrivastava commented on debugger-guide.md
> +If running and debugging is not yet configured (no `launch.json` has been created), VS Code shows the Run start view.
Add screenshots as well to make it more descriptive

2024-02-10 13:07 UTC, PranshuSrivastava commented on debugger-guide.md
> +You can either add more objects in the "configurations" array or modify the "args" property within a single object to add more commands.
Give an example here on how to use more flags with this configuration.

2024-02-10 13:07 UTC, PranshuSrivastava commented on debugger-guide.md
> +                "<path_to_executable>",
I think we can also use the docker run command here and not just the path to the executable file

2024-02-14 08:15 UTC, officialasishkumar commented
Done @PranshuSrivastava

2024-02-15 19:14 UTC, PranshuSrivastava requested changes

2024-02-15 19:14 UTC, PranshuSrivastava commented on debugger-guide.md
> +        "/home/coding/open-source/keploy/samples-go/gin-mongo/test-app-url-shortener",
You haven't shown how to pass env variables, we also need that sometimes

2024-02-15 19:14 UTC, PranshuSrivastava commented on debugger-guide.md
> +        "/home/coding/open-source/keploy/samples-go/gin-mongo/test-app-url-shortener",
don't use hardcoded values like this in examples, just say, path to binary

2024-02-15 19:14 UTC, PranshuSrivastava commented on debugger-guide.md
> +                "<path_to_executable>", // We can also put docker run command here.
there is no point of using a docker run command here, as the breakpoints will not work. Have you tested it before adding the comment?

2024-03-06 06:09 UTC, PranshuSrivastava commented
Closing as this has already been added.

2024-03-06 06:09 UTC, closed without merging