Addition of version argument to installation script
keploy/keploy pull request #1640
Opened 2024-03-03 20:16 UTC by AhmedLotfy02

## Related Issue
  - 

Closes: #1639

#### Describe the changes you've made
Addition of version argument to installation script

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know if any test cases are added

Please describe the tests(if any). Provide instructions how its affecting the coverage.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
A clear and concise description of it.

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] New and existing unit tests pass locally with my changes.

## Screenshots (if any)

|        Original         |          Updated           |
|:-----------------------:|:--------------------------:|
| **original screenshot** | <b>updated screenshot </b> |

2024-03-04 06:13 UTC, slayerjain requested changes
we should also add some docs about this usage in the docs repo.

2024-03-04 12:48 UTC, AhmedLotfy02 commented on keploy.sh
> +        VERSION_TAG="v$VERSION"
@slayerjain  Done

2024-03-04 12:53 UTC, AhmedLotfy02 commented on keploy.sh
> +        curl --silent --location "https://github.com/keploy/keploy/releases/download/$VERSION_TAG/keploy_linux_arm64.tar.gz" | tar xz -C /tmp
@slayerjain Done adding it to amd section and docker section.

2024-03-04 13:07 UTC, AhmedLotfy02 commented
@slayerjain All edits requested are done.

2024-03-17 14:41 UTC, gouravkrosx commented
@AhmedLotfy02 Please resolve the merge conflicts.

2024-03-17 15:09 UTC, AhmedLotfy02 commented
@gouravkrosx Done.

2024-04-29 11:13 UTC, shivamsouravjha commented
@gouravkrosx any update on this?

2024-04-30 13:27 UTC, AhmedLotfy02 commented
@shivamsouravjha Done.

2024-07-04 10:11 UTC, shivamsouravjha commented
closing the PR as issue is solved

2024-07-04 10:11 UTC, closed without merging