Keploy server version
keploy/keploy pull request #216
Opened 2022-10-16 14:39 UTC by PankhudiB

## Related Issue
  - https://github.com/keploy/keploy/issues/206

Closes: #206

#### Describe the changes you've made
Log the version during keploy server startup. Inject the version during go build with ldflags

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.

Local run output by passing dummy version: 

<img width="980" alt="image" src="https://user-images.githubusercontent.com/20110396/196041547-c4a40c94-8cd9-47a6-b113-af3df19cbe4b.png">

2022-10-16 14:40 UTC, PankhudiB commented
I have read the CLA Document and I hereby sign the CLA

2022-10-19 08:09 UTC, slayerjain requested changes

2022-10-19 08:09 UTC, slayerjain commented on .github/workflows/main.yml
> +          git_hash=$(git rev-parse --short "$GITHUB_SHA")
@PankhudiB as discussed in the issue thread. We should have both the commit-sha and the git-tag logged for the version. We mostly use git-tag for versions but adding commit-sha can. help identify unreleased builds.

2022-11-03 09:10 UTC, slayerjain approved these changes

2022-11-03 09:10 UTC, merged