Added logs when test cases are passed.
keploy/keploy pull request #2173
Opened 2024-08-03 06:48 UTC by Deepakchowdavarapu

## Related Issue
- Current test pipelines are not showing logs when all tests are passed
Closes: #2156

#### Describe the changes you've made
Modified the custom GitHub Action (tester) to always capture and display logs, regardless of test outcome. Updated the action.yml file to include a new step that consistently outputs test logs.

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue)

## Please let us know if any test cases are added
No new test cases were added. This change affects how existing tests are reported, improving visibility of test execution for both successful and failed runs.

#### Describe if there is any unusual behaviour of your code(Write `NA` if there isn't)
NA

## Checklist:
- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] My changes generate no new warnings.
- [x] I have added tests that prove my fix is effective or that my feature works.
- [x] New and existing unit tests pass locally with my changes.

2024-08-03 07:12 UTC, Deepakchowdavarapu commented
@Sarthak160 please review

2024-08-06 03:09 UTC, Sarthak160 commented
@Deepakchowdavarapu, Please sign the CLA, Also check your changes are breaking the current test pipline.

2024-08-06 03:11 UTC, Sarthak160 commented
Also when I am seeing the logs, I am still not able to see the full logs of the passed testset.

2024-08-06 07:36 UTC, Deepakchowdavarapu commented
recheck

2024-08-06 07:39 UTC, Deepakchowdavarapu commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/keploy/keploy/tree/main/.github/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **2** out of **3** committers have signed the CLA.✅ @Sonichigo✅ @Sarthak160❌ @DeepakchowdavarapuYou can retrigger this bot by commenting **recheck** in this Pull Request

recheck

2024-08-06 07:45 UTC, Deepakchowdavarapu commented
I have read the CLA Document and I hereby sign the CLA

2024-08-06 07:45 UTC, Deepakchowdavarapu commented
recheck

2024-08-06 07:48 UTC, Deepakchowdavarapu commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/keploy/keploy/tree/main/.github/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **2** out of **3** committers have signed the CLA.✅ @Sonichigo✅ @Sarthak160❌ @DeepakchowdavarapuYou can retrigger this bot by commenting **recheck** in this Pull Request

recheck

2024-08-06 07:50 UTC, Deepakchowdavarapu commented
recheck

2024-08-06 07:52 UTC, Deepakchowdavarapu commented
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://github.com/keploy/keploy/tree/main/.github/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> _**I have read the CLA Document and I hereby sign the CLA**_
> 
> **2** out of **3** committers have signed the CLA.✅ @Sonichigo✅ @Sarthak160❌ @DeepakchowdavarapuYou can retrigger this bot by commenting **recheck** in this Pull Request

recheck

2024-09-03 11:44 UTC, PranshuSrivastava requested changes

2024-09-03 11:44 UTC, PranshuSrivastava commented on .github/workflows/sample-run.yml
> +          go test -v ./... | tee test-output.log
You don't need to use go test, you need to show the logs from the keploy test command that is given in the shell scripts.

2024-10-12 11:10 UTC, Sarthak160 commented
@Deepakchowdavarapu Are you still working on this ?

2024-12-20 12:46 UTC, Hermione2408 commented
Closing this PR as it has been inactive for a long time. Feel free to reopen if needed.

2024-12-20 12:46 UTC, closed without merging