fix: Fixed mysql_golang_linux workflow
keploy/keploy pull request #2289
Opened 2024-09-13 12:39 UTC by ayush3160

## What does this PR do?
This PR fixes the random failing of mysql_golang_linux workflow.

## Related PRs and Issues

Closes: #2286 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:
- [x] Have you read the [Contributing Guidelines on issues](https://keploy.io/docs/keploy-explained/contribution-guide/)?
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

2024-09-16 04:13 UTC, khareyash05 requested changes
Try running the commands mentioned in the pipeline on your locale, and understand these commands, you will find cases that why sometimes there are cases of desultory commands

2024-09-16 04:13 UTC, khareyash05 commented on .github/workflows/test_workflow_scripts/golang-mysql-linux.sh
> +sed -i 's/global: {}/global: {"body": {"updated_at":[]},"header" : {"Content-Length" : []}}/' "$config_file"
Content Length can never come in the noisy field, as noisy fields are those which are to be ignored while replaying, if the content length itself doesnt match for example- the length of the response ,we cant process it further. L

2024-09-19 10:17 UTC, shivamsouravjha approved these changes
LGTM!

2024-09-19 10:18 UTC, shivamsouravjha approved these changes

2024-09-19 10:19 UTC, merged