Typos Fixed: Articulation Improved for Project Outlook
keploy/keploy pull request #2295
Opened 2024-09-20 10:03 UTC by engagepy

- corrected typos
- corrected fragmentation error :)
- simplified actionable step messages where required
- document now reads without any articulation flaw, as it should be for such a great project

## What does this PR do?

Improves readability, fixes typos and holds the README.md at a higher standard of articulation that it was.

## Related PRs and Issues

Null

Closes: #[issue number that will be closed through this PR]

## Type of change

- [x] Improved README.md update only

## Please let us know test plan followed

Locally

Please describe the tests(if any). Provide instructions how its affecting the coverage.

## Checklist:
- [x] Have you read the [Contributing Guidelines on issues](https://keploy.io/docs/keploy-explained/contribution-guide/)?
- [x] My code follows the style guidelines of this project.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have made corresponding changes to the documentation.
- [x] New and existing unit tests pass locally with my changes.

2024-09-20 10:04 UTC, engagepy commented
I have read the CLA Document and I hereby sign the CLA

2024-09-20 10:13 UTC, shivamsouravjha commented on README.md
> +Keploy's newly launched world's first unit test generator(ut-gen) implementation of [Meta LLM research paper](https://arxiv.org/pdf/2402.09171), it understands code semantics and generates meaningful
shouldn't it be Keploy has newly?

2024-09-20 10:16 UTC, shivamsouravjha requested changes

2024-09-20 10:52 UTC, engagepy commented on README.md
> +Keploy's newly launched world's first unit test generator(ut-gen) implementation of [Meta LLM research paper](https://arxiv.org/pdf/2402.09171), it understands code semantics and generates meaningful
Sure.

2024-09-20 10:52 UTC, engagepy commented on README.md
> +- **Improve edge cases**: Extend and improve the scope of atuomated tests to cover more complex scenarios, often missed manually.
On it.

2024-09-20 10:52 UTC, engagepy commented on README.md
Noted.

2024-09-20 10:52 UTC, engagepy commented on README.md
> +> ####  **If You Had Fun:** Please leave a 🌟 star on this repo!  It's free == a smile. 😄 👏
Roger

2024-09-20 10:52 UTC, engagepy commented on README.md
> +If you or your organisation is using Keploy? That’s great. Please add yourselves to [**this list,**](https://github.com/orgs/keploy/discussions/1765) and we'll send you goodies! 💖
Got it

2024-09-20 10:58 UTC, engagepy commented
@shivamsouravjha suggestions incorporated. Thanks !

2024-09-26 08:12 UTC, Sonichigo approved these changes

2024-10-01 17:37 UTC, khareyash05 approved these changes

2024-10-01 19:55 UTC, shivamsouravjha approved these changes

2024-10-01 20:01 UTC, merged