docs(readme): remove mongo from readme
keploy/keploy pull request #231
Opened 2022-11-03 10:43 UTC by slayerjain

The latest version of keploy no longer needs mongo to be running for saving test results/runs or test cases.

2022-11-03 12:14 UTC, slayerjain commented
@nehagup this looks fine to you?

2022-11-03 12:31 UTC, nehagup requested changes

2022-11-03 12:31 UTC, nehagup commented on README.md
> +export KEPLOY_MODE=record && go run handler.go main.go
shouldn't it be "record"?

2022-11-04 07:43 UTC, slayerjain commented on README.md
> +export KEPLOY_MODE=record && go run handler.go main.go
quotes doesn't matter here.

2022-11-04 07:45 UTC, merged