refactor: add header to check the last testcase
keploy/keploy pull request #2474
Opened 2024-12-17 11:02 UTC by Sarthak160

## What does this PR do?

(Provide a description of what this PR does and why it's needed.)

## Related PRs and Issues

- (Info about Related PR or issue)

Closes: #[issue number that will be closed through this PR]

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Code style update (formatting, local variables)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Please let us know test plan followed

Please describe the tests(if any). Provide instructions how its affecting the coverage.

## Checklist:
- [ ] Have you read the [Contributing Guidelines on issues](https://keploy.io/docs/keploy-explained/contribution-guide/)?
- [ ] My code follows the style guidelines of this project.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] New and existing unit tests pass locally with my changes.

2024-12-17 11:21 UTC, charankamarapu requested changes
Please address the comments rest looks fine.

2024-12-17 11:21 UTC, charankamarapu commented on pkg/service/replay/replay.go
> +		if idx == len(testCases)-1 && r.isLastTestSet {
Please check if you ignore test cases or select particular test case is this condition len(testCases)-1 is going to create any problem.

2024-12-17 11:21 UTC, charankamarapu commented on pkg/service/replay/replay.go
> +		if i == len(testSets)-1 {
Please check if you ignore test set or select particular test set is this condition len(testSets)-1 is going to create any problem.

2025-01-07 13:18 UTC, khareyash05 approved these changes

2025-01-07 13:23 UTC, charankamarapu approved these changes

2025-01-07 13:24 UTC, merged